name = "afl2-cloud-computing-api"
main = "src/index.ts"
compatibility_date = "2024-09-30"
compatibility_flags = ["nodejs_compat"]

# Variables available to Worker via env
[vars]
FIREBASE_PROJECT_ID = "afl2-7e2a5"
FIREBASE_DATABASE_URL = "https://afl2-7e2a5-default-rtdb.asia-southeast1.firebasedatabase.app"
FIREBASE_API_KEY = "AIzaSyBTNp9wM6oOoG0A7RxeGjvFAO_656OUnJk"
JWT_SECRET = "afl2-firebase-secure-jwt-secret-key-2026"

